name: panelizer
description: Responsive paneled layout.
version: 0.1.0
homepage: https://github.com/ookami-kb/panelizer

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  dfunc: ^0.9.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^6.0.0
  mews_pedantic: ^0.26.0

flutter:
  uses-material-design: true
