name: panelizer
description: "A new Flutter package project."
version: 0.0.1
# homepage:

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dfunc: ^0.9.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.26.0

flutter:
  uses-material-design: true
